print("Problem Statement")

q1 = input("What is your favorite programming language? ")
print(f"Your favorite programming language is: {q1}")
q2 = input("What is your favorite animal? ")
print(f"Your favorite animal is: {q2}")
q3 = input("What is your favorite color? ")
print(f"Your favorite color is: {q3}")
q4 = input("What is your favorite food? ")
print(f"Your favorite food is: {q4}")
q5 = input("What is your favorite movie? ")
print(f"Your favorite movie is: {q5}")